blank_issues_enabled: false
contact_links:
  - name: 🦆 skUnity Discord
    url: https://discord.gg/skript
    about: While this may not be Skript related, I'm usually hanging out there.
  - name: 🚰 SpigotMC Resource
    about: Not yet, maybe one day?!?!
